apiVersion: v1
kind: Secret
metadata:
  name: scalescope-actuator-token
  namespace: scalescope-demo
  annotations:
    kubernetes.io/service-account.name: scalescope-actuator
type: kubernetes.io/service-account-token
